spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: '{cipher}AYBEzjMQ7Zqfq2HnLnFGDSnlhANMSiHpaELyqJTutCeQYtQNYCyfpdZlLyhF2AV82lyzCFPy2OFm9cmFqcnVtH5efZQrhFEbVfERT4Qr8hj3MPMJU9ICn+Nn67dD4j2G+z600L9ye38ssP0lZoX6B931Tho/Nzc1OwZW09erQFns4GWZYabi9/kW3Uptos2sANTef1oRflpSZjtfu7dvK/f1/D6V/RpTby74CugbYeDLnc6sI4SPgTUL/IJ0LaLwcLMk+KwrYBuaKBZKFKZ7IeeYITiqyTBJTsHLCmD22OwLw9RtfpsUVYNRWxtX4i4oSfxtFbyAQDtHDNqbBGkw4Az690paPVZAYfZrNk+CJq4saI7QekA48dBBaG/xIRQv2yp0E6937yusAKRLf6XFwLzNFQqkGWwpsbnYEItKYxbLwTDcrmXKtrFFS4OSih/9t7VJLlPCXy6RG4cRQnkqEeiEMf5L8p3au/eiM37EziD8iKzppNtKG2TQ+6sdIkgXrP7taeA7YuafVUFSGPvxBH9a2aVwMdY+7AwgsEh2fKy9sQ=='
token:
  expired: 86400000
  secret: 7asdf5zx21sd6f8qv6s51dv32a1sd65cq16w5e1c32as1d651vq6w5e13v21as365d1v6q5s1eva3s21dv1651651651321321651a6sd5f16a5sd1f32as1d6f5a1sd3f2a1s6df51

gateway:
  ip: 192.168.0.8